apiVersion: v1
kind: Service
metadata:
  name: mysite
spec:
  type: ClusterIP
  selector:
    app: mysite
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-external
spec:
  type: LoadBalancer
  selector:
    app: mysite
  ports:
  - name: http
    port: 80
    targetPort: 8080
